name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  mcp-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install --frozen-lockfile || pnpm install
      - run: pnpm -w -F @canopy/attest build
      - run: pnpm -w -F mcp-server build
      - run: pnpm -w -F mcp-server test

  foundry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
          cache: true
      - name: Build & test
        working-directory: contracts
        run: |
          forge --version
          forge build -q
          forge test -vvv
